stages:
  build:
    nodeLabel: nvm
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install
        ENVIRONMENT=devint npm test
    filesToStash:
      - "**"
  prepublish:
    nodeLabel: nvm
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm i --no-save
        npm run build
    filesToStash:
      - ".webpack/"
  deployDevInt:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless@"<4.0.0"
        ENVIRONMENT=devint SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted npm run deploy
  deployUat:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless@"<4.0.0"
        ENVIRONMENT=uat SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted npm run deploy
  deployProd:
    nodeLabel: nvm-deployer
    steps:
      - |
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        npm install -g npm
        npm install -g serverless@"<4.0.0"
        ENVIRONMENT=prod SKRIPTS_DEPLOYMENT_BUCKET=dwolla-encrypted npm run deploy
